### PR TITLE
Revision of the handling of Docker secrets in S6

### LINKED ISSUE #346: Passphrase env vars with special characters no longer work with 1.8.13
As of docker-borgmatic 1.8.13, some Borg passphrases that worked fine with 1.8.12 no longer work. For instance:

```bash
$ docker run --rm -e BORG_PASSPHRASE='`' ghcr.io/borgmatic-collective/borgmatic:1.8.13
[custom-init] Docker CLI variable not set, skipping...
[custom-init] No custom packages found, skipping...
/etc/s6-overlay/env/cron-env: line 1: unexpected EOF while looking for matching ``'
-----------------------------------
Software Versions:
...
```

Which, if cron is actually configured and runs, leads to a Borg error about: `passphrase supplied in BORG_PASSPHRASE, by BORG_PASSCOMMAND or via BORG_PASSPHRASE_FD is incorrect`.

Whereas with 1.8.12:

```bash
$ docker run --rm -e BORG_PASSPHRASE='`' ghcr.io/borgmatic-collective/borgmatic:1.8.12
[custom-init] Docker CLI variable not set, skipping...
[custom-init] No custom packages found, skipping...
-----------------------------------
Software Versions:
```

And then if cron is actually configured, the passphrase comes through correctly and there's no error from Borg.

I believe the problem was likely introduced in #331 and specifically in https://github.com/borgmatic-collective/docker-borgmatic/pull/331/files#diff-df5fc4ba71d9f961534c2d65215e50da1befb1f2a16c4a03c58eba442f8c5dc3

It's possible that a backtick is not the only special character broken in this way by 1.8.13.

### PR DESCRIPTION
**Pull request by Psycho0verload**
Complete revision of the handling of Docker Secrets with S6 overlay after borgmatic:1.8.13 caused errors in the implementation.

**The following things have been changed:**
- Revision of Docker Secrets with S6
- Documentation adapted
- Bump python from 3.12.5-alpine3.19 to 3.12.7-alpine3.19
- Bump S6_OVERLAY_VERSION from 3.1.6.2 to 3.2.0.2

### Warning
Docker Secrets must now be defined differently. Instead of `*_FILE` now `FILE__*`

### Testing
- Build the Image with `docker build -t borgmatic:testing .`
- Run `docker run --rm -e BORG_PASSPHRASE='`' borgmatic:testing`

### Docker Secrets
- With the changes in Docker Secrets and in compliance with the documentation, the Secrets continue to work properly

Closes #346, #358

### CODE REVIEW

**Comment by Psycho0verload** [comment]
@modem7 @grantbevis

**Review by grantbevis — DISMISSED** [review]
LGTM

**Review by modem7 — APPROVED** [review]
LGTM - sorry it took so long to check!

Only thing I'd add is: "Borgmatic v1.9.0 has just been released, shall we add that to this PR as well? This is an optional comment, and not in any way a requirement to close/merge."

**Comment by Psycho0verload** [comment]
I have also installed the [update](https://github.com/borgmatic-collective/docker-borgmatic/pull/360).
I can't merge even with a review @grantbevis

**Review by grantbevis — APPROVED** [review]

**Pull request merged**
