### PR TITLE
Update Dockerfile + requirements.txt

### PR DESCRIPTION
**Pull request by modem7**
Updates to Alpine 3.16 + adds additional packages (build failed without them - we may need to investigate further).
Utilises pypi index.
Clean up Dockerfile to reduce layers + chmods binaries.

Once we're happy with the base image, I can create a PR for the other two.

### CODE REVIEW

**Comment by modem7** [comment]
Regarding the pypi index: 

If BorgBackup or llfuse has a release, it's better to wait until the index is updated by myself as that will reduce build time significantly. 

If Borgmatic has a release, it's fine to go ahead without waiting as they have pure python wheels already on pypi, so it won't make too much of a difference.

**Comment by grantbevis** [comment]
@modem7 - Good work dude, is this safe to merge?

**Comment by modem7** [comment]
> @modem7 - Good work dude, is this safe to merge?

Heya,

For base, absolutely.

For the two supporting images that rely on base image as a FROM directive? I have not tested as of yet.

**Comment by grantbevis** [comment]
I think this is our opportunity to get rid of the other two images and just move to have a single base image with apprise in it - Fancy adding apprise to this PR for the base?

**Comment by modem7** [comment]
> I think this is our opportunity to get rid of the other two images and just move to have a single base image with apprise in it - Fancy adding apprise to this PR for the base?

Dun n dun!

**Comment by grantbevis** [comment]
I would prefer not to rely on other images/repositories and to keep everything built here. There's merge conflicts on this PR too

**Comment by modem7** [comment]
> I would prefer not to rely on other images/repositories and to keep everything built here. There's merge conflicts on this PR too

Ah no, misunderstanding there. We'd create it using the borgmatic-collective repo so it'd be completely isolated to our maintenance. 

I was more showing how I've done Dockerfile rather than anything else. 

We'd only need to change FROM `modem7/borgmatic-docker:latest` to `FROM b3vis/borgmatic:latest`

**Comment by modem7** [comment]
Updated Dockerfile to Alpine 3.16.1 which fixes https://github.com/borgmatic-collective/docker-borgmatic/pull/139

**Review by grantbevis — APPROVED** [review]
Lets do it - sorry to leave this hanging

**Pull request merged**
