### PR TITLE
Remove unnecessary VOLUME definitions in Dockerfile

### PR DESCRIPTION
**Pull request by kaechele**
This removes VOLUME definitions for locations in the container where we expect the user to bind their own storage locations or locations where we don't expect the build process to place files.
The impact of this change is that users using docker compose will not see unused but declared VOLUMEs being created as anonymous volumes.

### CODE REVIEW

**Comment by kaechele** [comment]
To further elaborate:

Functionally, all a `VOLUME` declaration does in a `Dockerfile` is to discard any subsequent changes to that directory from build steps in that `Dockerfile`.
I can appreciate it's declaratory value for documentation purposes, but it has side-effects:
Each `VOLUME` declaration that is not met with a corresponding volume in a docker compose scenario will lead to an anonymous volume created by docker compose. As an example, in normal backup operations, using the borgmatic docker container in a scenario where remote repositories are used exclusively will never use the `/mnt/borg-repository` volume that is declared. It will, however, when used with docker compose, stick around as an empty, anonymous volume after the containers are removed creating cruft.

On the other hand, the volumes we declare in the `Dockerfile` to store state (such as the cache directories) would be reasonable to keep around and they are also always used in any case. So they'd be fine even as an anonymous volume.

**Comment by grantbevis** [comment]
I agree, this has been raised a few times before. @modem7 - do you concur dude?

**Review by grantbevis — APPROVED** [review]

**Comment by modem7** [comment]
Hmmm, unsure about this one.

Given that the majority of users are indeed using compose, creating anonymous docker volumes are imo, a wanted feature, lest a user not bind a suitable location and lose data at next (container) reboot.

It may be worthwhile revisiting the amount of volumes required, but they are documented (and enacted) for a good reason.

**Comment by modem7** [comment]
Hmmm, unsure about this one.

Given that the majority of users are indeed using compose, creating anonymous docker volumes are imo, a wanted feature, lest a user not bind a suitable location and lose data at next (container) reboot.

It may be worthwhile revisiting the amount of volumes required, but they are documented (and enacted) for a good reason.

---

Thinking on this further, I would like the VOLUME mounts to stay in the dockerfile, however, commented out for now until we review our documentation a bit further (probably after the other images are removed).

So from a functional POV, the dockerfile wouldn't have any volume mounts predefined, but they'd still be there for doco as code purposes.

**Comment by kaechele** [comment]
> I would like the VOLUME mounts to stay in the dockerfile, however, commented out for now until we review our documentation a bit further (probably after the other images are removed).

I think that'd be a good compromise.

To gain more clarity let's go through the `VOLUME` declarations one by one. And, please, add or correct anything that I'm missing.

**NOTE**: If the user invokes the container with a `docker run` the `VOLUME` directive has no functional effect anyway. No anonymous volumes are created in that instance, so data loss on undefined volumes would occur regardless of whether the `VOLUME` was declared in the `Dockerfile` or not. This means the scenarios below all assume docker compose is being used, where there is a functional difference whether a `VOLUME` is declared or not.

### `VOLUME /mnt/source`
The directory where data is backed up from / restored to. Generally this would not make sense to have as an anonymous volume. While not impossible (users will be users :smile:) it is extremely unlikely the user would not configure anything here.
In a docker compose setup this will create an anonymous volume even if the user binds directories into this path as a subfolder (e.g. a bind mount into `/mnt/source/dir1` will still result in an anonymous volume being created for `/mnt/source`).

### `VOLUME /mnt/borg-repository`
This is where in the default configuration the borg repository would land. It is unlikely a user would not want this persisted. This is a case where, if we got rid of that `VOLUME`, there may be data loss (of the borg repository) due to user error in the following scenario:
The user
1. uses docker compose
2. uses the default config
3. doesn't ensure that location is persisted (either through a named volume or a bind mount)

### `VOLUME /root/.borgmatic`
This directory currently holds borgmatic state information (see #211). While not a requirement, it's generally useful to persist this between container runs. The user would not need to interact with this data though, and it wouldn't require backup of itself. So storing this in an anonymous volume is fine from my perspective as it improves user experience.
Not persisting this data would result in borgmatic running checks on repositories more frequently than defined in a non-default user configuration.

### `VOLUME /etc/borgmatic.d`
This contains user defined configuration. There is no reason for this volume to exist if the user does not wish to add their own configuration.

### `VOLUME /root/.config/borg`
Borg places its repository security information here, specifically the nonce files ensuring the integrity of the encryption.
Not persisting these files can result in a weakened security as they can be helpful in detecting tampering of the remote repository and preventing attacks weakening the encryption.
As such, it's generally advisable to keep these persisted. However, they are also stored in the repository and will be recreated when missing. Again, anonymous volume is fine here as it improves user experience.

### `VOLUME /root/.ssh`
This directory is unused if a user only uses local repositories. If the user does use SSH repositories they would have to place their keys and `known_hosts` file in this directory. As such they would have to sensibly configure this either way.
There is no effect of this directory being missing if the user does not use SSH repositories.

### `VOLUME /root/.cache/borg`
The Borg cache is useful to have around as it speeds up backup runs. It's nonessential though, so keeping it in an anonymous volume is fine as it improves user experience.

**Comment by kaechele** [comment]
As a rule I think we could define:

Something gets a `VOLUME` declaration if it is:
1. creates a significant risk of data loss to the user if left undefined and unpersisted
2. state data essential to the operation of backup or restore operations
3. state data that is a clear improvement in user experience in any scenario (eg. regardless of what type of repository is used)

**Pull request closed without merging**
