### PR TITLE
feat: use docker secrets, fix up markdown

### PR DESCRIPTION
**Pull request by sammcj**
- Optionally use Docker secrets to improve security.
- Fixup Markdown (linting/formatting/spelling).
- Minor shell scripting fixes.

Couldn't find a relevant open issue, but does relate to #47

### CODE REVIEW

**Comment by sammcj** [comment]
@borgmatic-collective @jetchirag

**Comment by jetchirag** [comment]
Thank you for all the formatting fixes. I missed quite many.

**Comment by sammcj** [comment]
Just wondering how this is going? It would be good to run from the main Borgmatic repo rather than from my fork 😅

**Comment by ThorpeJosh** [comment]
Hey @sammcj, this would be a great addition. I try to use docker secrets whenever possible but unfortunately not all docker services support them, so I fully support you in this PR.

I had a quick look at the PR and it was very difficult to read due to all the formatting changes. I would suggest opening a separate PR just to fix all the markdown formatting and keep this one strictly related to docker secrets. It will make it easier to review and much more likely to be merged.

Cheers

**Comment by grantbevis** [comment]
> Hey @sammcj, this would be a great addition. I try to use docker secrets whenever possible but unfortunately not all docker services support them, so I fully support you in this PR.
> 
> I had a quick look at the PR and it was very difficult to read due to all the formatting changes. I would suggest opening a separate PR just to fix all the markdown formatting and keep this one strictly related to docker secrets. It will make it easier to review and much more likely to be merged.
> 
> Cheers

I second this, if you could submit two PR’s it will be easier for me to review

**Comment by modem7** [comment]
Given we've just merged #303, how much of this is still pertinent?

**Comment by sammcj** [comment]
Good call @modem7 , I'll close this off for now. Cheers.

**Pull request closed without merging**
