### PR TITLE
Upgrade to Alpine 3.17

### PR DESCRIPTION
**Pull request by grantbevis**

### CODE REVIEW

**Comment by grantbevis** [comment]
Solves https://github.com/borgmatic-collective/docker-borgmatic/issues/180#issuecomment-1329960444

**Comment by modem7** [comment]
This image is no longer available, so we can close this for now. 

Latest would be [3.11.0-alpine3.16](https://hub.docker.com/layers/library/python/3.11.0-alpine3.16/images/sha256-a71e8ff8638a437e4cd8ad80a609235af54bc04d75e1aa2832146595e31d83bc?context=explore)

**Comment by modem7** [comment]
Can confirm that it builds with no issue. No further testing has been done on this end however apart from building the image.

Same with [Python 3.11](python:3.11-alpine3.17)

**Review by modem7 — APPROVED** [review]

**Review by modem7 — APPROVED** [review]
@grantbevis

Can confirm that it builds with no issue. No further testing has been done on this end however apart from building the image.

Same with python:3.11-alpine3.17

**Pull request merged**
