### PR TITLE
use postgresql 16 client in the image

### PR DESCRIPTION
**Pull request by Belphemur**
For now, the client for 16 is only available in edge. This is needed if the user is dumping databases from a postgres 16 server.

Without this, the pg_dump will fail.

This is only temporary until alpine add the 16 client to main

### CODE REVIEW

**Comment by grantbevis** [comment]
Does this remove functionality for others i.e pg_dump 16 doesn't support Postgres 12 or something

**Comment by grantbevis** [comment]
@modem7 another thing where the s6 setup would shine dude

**Comment by modem7** [comment]
> @modem7 another thing where the s6 setup would shine dude

We can certainly investigate a custom startup section where people can add their own packages or something, or simplify it and have a ENV var which people can add their own values which are the installed during container startup.

e.g. https://github.com/modem7/docker-borgmatic/blob/master/base-fullbuild/root/etc/s6-overlay/s6-rc.d/svc-cron/run#L3-L10

**Comment by Belphemur** [comment]
pgclient lib are always backward compatible with older server. Or that has been my experience in the past, since you need to use some of those tools when doing database migration from major versions to other major version (like 15 -> 16).

About the image itself, it would be great to remake it from linuxserver base, they have a great alpine one with proper user management etc ...
https://github.com/linuxserver/docker-baseimage-alpine

**Comment by modem7** [comment]
> Hello,
> 
> pg_dump 16.1 is available in alpine 3.19.
> 
> So I suggest to rebase the Dockerfile to 3.11-alpine3.19 (from python:3.11.5-alpine3.18 currently) or better directly use python:3.11-alpine or python:3-alpine
> 

I'm just testing `python:3.11.7-alpine3.19` now for viability.

**Comment by modem7** [comment]
`python:3.11.7-alpine3.19` fails build as there are packages missing in the Alpine repos (like `openssl1.1-compat`).

`python:3.11.7-alpine3.18` seems to work, however. I'm doing a backup now to see how it goes.

**Comment by jejbq** [comment]
FYI
The above patch works for me and I am able to backup both Postgres 16 (postgres:16-bookworm) and MariaDB 11 (mariadb:11). In terms of security, it would be nice to add "apk upgrade --update --no-cache" in order to apply security updates to Alpine if they are not yet included in python docker image.

**Comment by jejbq** [comment]
What's wrong with using alpine 3.19 with openssl instead of openssl1.1-compat?

so I think python:3.11-alpine3.19 or python:3.11-alpine can be a good fit no?

I made backups overnight, including files, postgres 16, mariadb, etc. without any problems.

**Comment by modem7** [comment]
> What's wrong with using alpine 3.19 with openssl instead of openssl1.1-compat? https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/
> 
> so I think python:3.11-alpine3.19 or python:3.11-alpine can be a good fit no?
> 
> I made backups overnight, including files, postgres 16, mariadb, etc. without any problems.

Sorry for taking so long to reply, work was slammed. 

After doing some extra testing, I concur, we can use openssl instead of compat. 

I propose the following:

Use `python:3.11.7-alpine3.19` as the image. 

Use `openssl` instead of `openssl1.1-compat`. 

I'd be happy to approve with those changes in place.

**Comment by Belphemur** [comment]
@modem7 changes requested are done :)

**Comment by JeremyKennedy** [comment]
is there a way I can use this right away? currently my databases are not being backed up, which isn't great.

**Comment by modem7** [comment]
> is there a way I can use this right away? currently my databases are not being backed up, which isn't great.

You can build your own image and utilise the dockerfile present.

Over the weekend I'll see what I can do to expedite either this or a slightly new direction I'd like to go which will still achieve the same thing.

**Comment by JeremyKennedy** [comment]
Thank you for the reply. I have this deployed on Unraid, so it's not straightforward to build images for use there, ideally I'd point to a public Docker repo using a specific tag. I suppose I can set that up myself tomorrow by building on my main pc and pushing to Dockerhub using my own repo.

**Comment by JeremyKennedy** [comment]
well would you look at that, I've done it! 

value to put in unraid repo field: `jibbsisme/borgmatic-pg16:v2`

image on dockerhub: https://hub.docker.com/r/jibbsisme/borgmatic-pg16

quick and dirty how I did this, for anyone who wants to without trusting my image:

set up dockerhub:
1. make an account
2. create a repo
3. `docker login`

build and push:
1. clone the repo
2. pull this pull request
3. rebase it on top of master
5. `docker build -t "jibbsisme/borgmatic-pg16:v2" .` (replace `jibbsisme` with your username and `borgmatic-pg16` with your repo name)
6. `docker push jibbsisme/borgmatic-pg16:v2` (same replacements as above)

**Pull request closed without merging**
