### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by trash-it**
Add apprise state definitions

### CODE REVIEW

**Comment by trash-it** [comment]
From the README it was not obviously that its necessary to create states for apprise notifications

**Comment by witten** [comment]
LGTM! I'll clarify this in the main borgmatic docs as well.

**Review by modem7 — APPROVED** [review]
LGTM

**Review by modem7 — APPROVED** [review]

**Comment by modem7** [comment]
@grantbevis - for some reason the approval isn't working as expected. Are you able to merge?

**Review by grantbevis — APPROVED** [review]

**Pull request merged**
