### PR TITLE
Crontab changes

### LINKED ISSUE #170: Local docker build fails
I've tried to build the docker [base](https://github.com/borgmatic-collective/docker-borgmatic/tree/master/base) image locally with Docker version 20.10.20 and ran into several errors:

#### 1st try
```sh
docker build .
#dockerfile parse error line 32: Unknown flag: link
```

#### 2nd try
I have added `# syntax=docker/dockerfile:1.4` on top of the [Dockerfile](https://github.com/borgmatic-collective/docker-borgmatic/blob/master/base/Dockerfile).

```sh
DOCKER_BUILDKIT=1 docker build .
#13 38.31       test compiling /tmp/tmp_ruamel_c7_6zu3m/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_c7_6zu3m/test_ruamel_yaml.c
#13 38.31       Exception: command 'gcc' failed: No such file or directory
```

Is there anything more to consider when building the image? I would appreciate your help :-)

### PR DESCRIPTION
**Pull request by modem7**
Added ENV vars for crontab, removed old file/way of doing things.

Two new ENV vars have been added:

```
$CRON
$CRON_COMMAND
```

If these are unset, they will default to Borg defaults.

Example usage:
    environment:
      - CRON=0 5 * * *
      - CRON_COMMAND=borgmatic --stats -v 0 2>&1
      
---

Edit (31/10/2022): https://github.com/borgmatic-collective/docker-borgmatic/pull/150/commits/9a3e29d68bab8c202881b92f49f5e3226d57a0f8 fixes #170

### CODE REVIEW

**Comment by Skydiver84de** [comment]
Cool idea, but what if someone had two lines before in crontab.txt? E.g. one for a daily prune create and one for a monthly check?

**Comment by modem7** [comment]
I might be able to add something where it can monitor a particular folder for additional files.

I'll investigate further

**Comment by grantbevis** [comment]
I agree with @Skydiver84de I’d rather allow people to edit their own crontab.txt’s. I implemented something like this at ${work} where in the image I pre set the “top” of the file in /crontab-pre

then I 

cat /crontab-top > crontab-build.txt
cat /crontab.txt >> crontab-build.txt
crontab crontab-build.txt

Not sure if that would work for us here

**Comment by toastie89** [comment]
I like the idea. This will be a breaking change and should be part of a major release.

You might go for CRON_10, CRON_22,..  and iterate over those variables.

Is there a special reason why to split Cron and CRON_COMMAND?

**Comment by modem7** [comment]
> I agree with @Skydiver84de I’d rather allow people to edit their own crontab.txt’s. I implemented something like this at ${work} where in the image I pre set the “top” of the file in /crontab-pre
> 
> then I 
> 
> cat /crontab-pre > crontab-build.txt
> cat /crontab.txt >> crontab-build.txt
> crontab crontab-build.txt
> 
> Not sure if that would work for us here

I've got a potentially better idea, will post later/tomorrow once I flesh it out! 

> Is there a special reason why to split Cron and CRON_COMMAND? 
> 
Aye, more for basic users vs advanced users. 

For basic users, it's less likely to mess up a simple cron job they can c+p than to mess up the entire line. 

It also allows for different values available to borgmatic to be changed at will without much hassle for those who wish it.

**Comment by modem7** [comment]
Would something like this be good?

For single extra requirements:

```
    environment:
      - CRON=$BORG_CRON
      - CRON_COMMAND=$BORG_CRON_COMMAND
      - EXTRA_CRON=0 5 2 * * mycommand
```

For multiple:

```
    environment:
      - CRON=$BORG_CRON
      - CRON_COMMAND=$BORG_CRON_COMMAND
      - |
        EXTRA_CRON=
        0 5 2 * * mycommand1
        0 7 1 * * mycommand2
      - BORG_PASSPHRASE=$BORG_PASSPHRASE
```

**Comment by grantbevis** [comment]
I like this
```
      - |
        EXTRA_CRON=
        0 5 2 * * mycommand1
        0 7 1 * * mycommand2
```

But I don't like setting the `CRON=$BORG_CRON` and `CRON_COMMAND` etc - I'd rather cron actually be a secondary thought in this container and that we write it so people could use it for adhoc backups but we also have the ability to accept a crontab.

Forgive me but I am also not understanding the need to change from a `crontab.txt` I understand using envars can be neater but it's a big breaking change for lots of users I'd rather not tackle

**Comment by modem7** [comment]
I mean, it's not difficult to disable cron completely, just don't replace the file.

Can happily make a change where if CRON is empty or set to disabled or something it just wouldn't overwrite the crontab, but going to an ad-hoc model as primary would be just a breaking change.

The way I see it, the reliance on a config file in a docker environment isn't great. It's awful for reproduceability, doesn't scale well, and just generally goes against the entire purpose of Docker being ephemeral. 

It's a necessary evil in many cases, but in our case, we can work towards putting as much as we can into an env var, and any further changes can be added by some other method, especially since Borgmatic can now parse env vars in configs. 

I'm happy to hear alternative solutions, with the above kept in mind.

**Comment by modem7** [comment]
Here, just for a TLDR of the above, would this script deal with: 

1. Adhoc mode as raised by @grantbevis 
2. Custom crontab as raised by @Skydiver84de 
3. Env vars as per this PR
4. Resolving breaking change as raised by @toastie89 

```shell
# Disable cron if it's set to disabled.
if [[ "$CRON" =~ ^(false|disabled|off)$ ]]; then
    echo "Disabling cron, removing configuration"
    crontab -r
    echo "Cron is now disabled"
# Apply default or custom cron if $CRON is unset or set (not null):
elif [[ -v CRON ]]; then
    CRON="${CRON:-"0 1 * * *"}"
    CRON_COMMAND="${CRON_COMMAND:-"borgmatic --stats -v 0 2>&1"}"
    echo "$CRON $CRON_COMMAND" > /etc/crontabs/root
    echo "Applying custom cron"
# If nothing is set, revert to default behaviour
else
    echo "Applying crontab.txt"
    crontab /etc/borgmatic.d/crontab.txt
fi

# Apply extra cron if it's set
if [ -v EXTRA_CRON ]
then
    echo "$EXTRA_CRON" >> /etc/crontabs/root
fi

# Current crontab var
crontab=$(crontab -l)

# Output cron settings to console
printf "Cron job set as: \n$crontab\n"
```

**Comment by grantbevis** [comment]
This looks good @modem7

**Comment by modem7** [comment]
> This looks good @modem7 

@grantbevis sweet, I'll do the necessary changes, and notify when it's pushed.

**Comment by modem7** [comment]
@grantbevis sorry it took so long - been slammed at work. 

This should work as expected with all scenarios in place.

We'll need to think about how to word the update to the readme to include the additional ENV vars at some point:

```
CRON
CRON_COMMAND
EXTRA_CRON
```

**Review by grantbevis — COMMENTED** [review]
Looks good @modem7 just to confirm have you tested the full function of this? I don't have the ability to test. But trust your word if you have, also did the docs get updated to follow this change?

Might be worth us having a notice up on the readme

**Comment by modem7** [comment]
> Looks good @modem7 just to confirm have you tested the full function of this? I don't have the ability to test. But trust your word if you have, also did the docs get updated to follow this change?
> 
> Might be worth us having a notice up on the readme

Heya, 

Yupper, I can confirm that I've tested as much as I'm able to on this end with standard crontab syntaxes. 

The docs have not yet been updated, we probably need to figure out how we're going to be communicating this and what the best way to document it is (format etc).

**Comment by psi-4ward** [comment]
Does docker(-compose) support the array syntax?

```yaml
  environment:
    - "CRON[]= 0 5 2 * * command1"
    - "CRON[]= 0 5 2 * * command1"
```

Just an idea

**Comment by modem7** [comment]
> Does docker(-compose) support the array syntax?
> 
> ```yaml
>   environment:
>     - "CRON[]= 0 5 2 * * command1"
>     - "CRON[]= 0 5 2 * * command1"
> ```
> 
> Just an idea 
> 

I had a quick look, and on the face of it, it doesn't seem to.

If you're able to get it working, happy to have a look at it!

**Comment by psi-4ward** [comment]
> I had a quick look, and on the face of it, it doesn't seem to.

Looks like this is not supported cause not all shells support array-structs so I would stick to the following syntax
```yaml
  environment:
    EXTRA_CRON: |-
        0 5 2 * * command1
        0 7 1 * * command2
```

**Comment by modem7** [comment]
@grantbevis - Just for an FYI - the merge conflict is caused by updating to latest python 3.11 in this branch.

**Comment by modem7** [comment]
https://github.com/borgmatic-collective/docker-borgmatic/pull/150/commits/9a3e29d68bab8c202881b92f49f5e3226d57a0f8 fixes #170

**Comment by grantbevis** [comment]
Is this ready to go @modem7 ? Did we need to put a notice on the README?

**Comment by modem7** [comment]
We need to create some documentation for this but other than that - it's good to go. 

Would just a list of variables, defaults + possible options be sufficient? I can whip that up in markdown pretty quick.

**Comment by modem7** [comment]
Here's a quick set of doco (as markdown is weird, I've also put a quoted version below in, so it's easier to C+P):

# Variables
| Variable | Description | Default | Example Values |
| :----: | --- | --- | --- |
| CRON | Cron timing | Existing crontab or <br> `0 1 * * *` | `0 5 * * *` |
| CRON_COMMAND | Borgmatic command <br> that Cron runs. | `borgmatic --stats -v 0 2>&1` | `borgmatic --stats -v 2 2>&1` |
| EXTRA_CRON | Additional cron lines <br> for advanced usage. | Empty | ***See below*** |

### Example setup
```shell
      CRON: "0 5 * * *"
      CRON_COMMAND: "borgmatic --stats -v 0 2>&1"
      EXTRA_CRON: |-
        0 5 2 * * command1
        0 7 1 * * command2
```

---

````markdown
# Variables
| Variable | Description | Default | Example Values |
| :----: | --- | --- | --- |
| CRON | Cron timing | Existing crontab or <br> `0 1 * * *` | `0 5 * * *` |
| CRON_COMMAND | Borgmatic command <br> that Cron runs. | `borgmatic --stats -v 0 2>&1` | `borgmatic --stats -v 2 2>&1` |
| EXTRA_CRON | Additional cron lines <br> for advanced usage. | Empty | ***See below*** |

### Example setup
```shell
      CRON: "0 5 * * *"
      CRON_COMMAND: "borgmatic --stats -v 0 2>&1"
      EXTRA_CRON: |-
        0 5 2 * * command1
        0 7 1 * * command2
```
````

**Pull request closed without merging**
