### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by tomaszduda23**
fix mismatch between base image and ntfy

### CODE REVIEW

**Comment by grantbevis** [comment]
@modem7 - This would switch us back to alpine as the base - We only recently changed from alpine > python-alpine base

**Comment by tomaszduda23** [comment]
Now nfty does not work at all since it there is mismatch between python location.

**Comment by modem7** [comment]
Why are we still pursuing ntfy?

msmtp and ntfy should have been sunset in favour of apprise, which is why we decided to include it surely?

**Comment by grantbevis** [comment]
Yes... this is correct, I forgot @modem7 thanks bro.

@tomaszduda23 - ntfy is deprecated and we're switching to use apprise

**Comment by grantbevis** [comment]
> @grantbevis is there any examples in doc how to use apprise? You could remove ntfy images if you are not going to use it anymore (it is broken anyway).

Not in ours, theirs is good https://github.com/caronc/apprise

**Pull request closed without merging**
