### PR TITLE
Multiarch workflows

### PR DESCRIPTION
**Pull request by frutti93**
As discussed in https://github.com/b3vis/docker-borgmatic/issues/54.

To make this work you have to add DOCKER_USERNAME and DOCKER_PASSWORD to the repository secrets, containing the Docker-Hub login.

### CODE REVIEW

**Comment by PixelJonas** [comment]
+1 to this PR. Having this image available on ARM would be great!

**Comment by Sdub76** [comment]
Would this automate the pushing of updated builds to Docker Hub?  If so let me +1 so we can get container updates a little more frequently.

I maintain the Unraid Borgmatic template, which is based on this docker container and I'd rather not move to a more recently updated fork.

**Comment by b3vis** [comment]
I am going to spend some time looking at this as docker hub have stopped my account from doing automated builds as I'm not on a pro account. 

Thank you @Sdub76 for the unRAID template, I spotted that a while ago when I was still running unRAID and had a warm fuzzy feeling!

I think I might need to get some help on this image/repo to keep it up to date and run it as an organisation. If you're reading this and would like to assist please reply with a little bit of what you can bring to the table.

**Comment by frutti93** [comment]
> Would this automate the pushing of updated builds to Docker Hub? If so let me +1 so we can get container updates a little more frequently.
> 
> I maintain the Unraid Borgmatic template, which is based on this docker container and I'd rather not move to a more recently updated fork.

Yes it would, an image with "latest" tag would be automatically built for every push to master and version tagged images would be built for every pushed tag to master.

@b3vis If you would like to play around, you could just mirror and rename your repo and integrate this PR. The docker hub name will correspond to the repository name, so if you rename the clone it will not harm the original docker hub images.

**Comment by PixelJonas** [comment]
@b3vis if you need help setting up a [Quay.io](https://quay.io) Account ping me.

another alternative would be the [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) I never used that one though

**Comment by fschrempf** [comment]
> another alternative would be the [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) I never used that one though

or the [GitLab Container Registry](https://docs.gitlab.com/ee/user/packages/container_registry/) hosted on gitlab.com. But that would probably only make sense if the repo is also hosted on gitlab.com, or at least mirrored there.

**Comment by frutti93** [comment]
As it has been half a year since I opened the PR, is there any chance this will be integrated in the future? Can I do anything to help?

**Review by b3vis — APPROVED** [review]
Let's do this

**Comment by b3vis** [comment]
> As it has been half a year since I opened the PR, is there any chance this will be integrated in the future? Can I do anything to help?

I'm sorry this has taken me so long, I had forgotten if I am honest. I've enabled this now

**Comment by frutti93** [comment]
Nevermind, I thought so ;)

**Pull request merged**
