### PR TITLE
Mail subject and env enhancements

### PR DESCRIPTION
**Pull request by fschrempf**
The main goal of this PR is to enhance the subject line of e-mail notifications. Currently the subject of the e-mails look like this (created by cron):

```
cron: PATH=$PATH:/usr/bin /usr/bin/borgmatic --stats -v 2 2>&1
```

With this PR, they look like this:

```
 ✅ SUCCESS: Borgmatic Example Backup
```
```
 ❌ FAILED: Borgmatic Example Backup
```

I think it's quite obvious that this makes it much easier to see if there are problems as the subject line reflects the backup return status. Especially if you have multiple notifications from different sources in your mailbox.

Apart from this it is now possible to specify the recipients of the notifications in the docker environment.

What I don't really like is the current "abuse" of the `/etc/borgmatic.d` directory for all kinds of other files. IMHO this should be used only for borgmatic config files and the rest should be stored elsewhere. Also it would be nice to have default files for the crontab, and the init/run scripts inside the container image as the average user doesn't really need to mount customized versions anymore if everything can be setup via the environment. But these are separate issues for potential future PRs.

This is currently a draft until I have done some more tests. Any comments are welcome!

### CODE REVIEW

**Comment by fschrempf** [comment]
I fixed a small bug in the `crontab.txt` and updated the documentation. Please have a look and let me know if you think this is appropriate. Thanks!

**Comment by hatl** [comment]
the `MAILTO=log@example.com` in crontab should be removed, otherwise you would get 2 emails, right?

**Comment by fschrempf** [comment]
> the `MAILTO=log@example.com` in crontab should be removed, otherwise you would get 2 emails, right?

Right, fixed!

**Comment by fschrempf** [comment]
> BTW: having `BACKUP_COMMAND=...` in a file that's called `mailenv.sh` seems counter-intuitive to me.
> maybe rename it to env.sh?

Hm, yes that's true. I will change that. Another task for later will be to align the msmtp image and the base image.

**Review by grantbevis — APPROVED** [review]
Looks good to me

**Pull request merged**
