### PR TITLE
Optimise dockerfile

### PR DESCRIPTION
**Pull request by modem7**
Recreating https://github.com/borgmatic-collective/docker-borgmatic/pull/142 as discussed. 

@grantbevis @toastie89

### CODE REVIEW

**Comment by modem7** [comment]
Continuing on https://github.com/borgmatic-collective/docker-borgmatic/pull/142#issuecomment-1197215028

> Hi @modem7, looks like this change introduces two more packages (zstd, libxxhash), may I ask for what they are?

Heya @toastie89, 

I found that in alpine 3.16.x., borg refused to work properly without these being added in. 

Looking at recent builds however, this issue may have stopped being a thing. I'll retest now and report back. 

Unfortunately, I don't know enough about python to debug without assistance. I'm happy to assist with debugging.

**Review by grantbevis — APPROVED** [review]

**Comment by grantbevis** [comment]
I will wait for @toastie89's feed back before merging

**Comment by modem7** [comment]
@toastie89 That was it:

Borg refused to build without these dependencies. This change is a hangover from when I was testing local python wheel builds. 

Thanks for highlighting. These packages have now been moved to https://github.com/borgmatic-collective/pypi/blob/main/borgmatic/borgmatic_wheels.sh for building the wheels and are no longer required. 

I'm just finalising some testing, then I'll update the Dockerfile to remove if all working.

**Review by toastie89 — APPROVED** [review]
@modem7 , thanks for the update and the detailed explanation

**Pull request merged**
